version: '3'
services:
  restletapp:
    build: .
    volumes:
      - ./target:/worker
    working_dir: /worker
    command: restlet-app-1.1-jar-with-dependencies.jar
    container_name: restletapp
    ports: 
      - "8081:8080"
    depends_on:
      - banco
    links:
      - "banco:banco-app"

  banco:
    image: mongo
    container_name: banco
    ports: 
      - "27017:27017"
